### ISSUE TITLE
리뷰 남겨요

### ISSUE THREAD

**Issue by devmizz** [jmjmjames/ssg-toy-project#1]
### 좋은점

- 인덴트가 정말 깔끔해서 보기 편했습니다.
- stream을 정말 잘 활용하셔서 가독성 높은 코드가 된 거 같습니다.
    
<img width="427" alt="image" src="https://user-images.githubusercontent.com/92210823/179639006-0395352b-4495-4d24-9b20-a8169dd25ecd.png">
    
- 서비스에선 modify, 레포지토리에선 update 네이밍을 채택하신 게 인상깊네요! 좋은 네이밍이라고 생각합니다!

### 아쉬운점

- 컨트롤러에서 너무 많은 일을 처리하고 있는 거 같습니다! 컨트롤러는 관문(?) 같은 역할만 하는 친구라서, 입출력 자체는 App.java에서 처리하고, 컨트롤러는 서비스로 넘겨주는 역할만 수행, 나머지 로직은 서비스에서 시행하는 게 좋지 않을까 싶습니다.

수고 많으셨습니다!

**Comment by jmjmjames** [comment]
> ### 좋은점
> * 인덴트가 정말 깔끔해서 보기 편했습니다.
> * stream을 정말 잘 활용하셔서 가독성 높은 코드가 된 거 같습니다.
> 
> <img alt="image" width="427" src="https://user-images.githubusercontent.com/92210823/179639006-0395352b-4495-4d24-9b20-a8169dd25ecd.png">
> 
> * 서비스에선 modify, 레포지토리에선 update 네이밍을 채택하신 게 인상깊네요! 좋은 네이밍이라고 생각합니다!
> 
> ### 아쉬운점
> * 컨트롤러에서 너무 많은 일을 처리하고 있는 거 같습니다! 컨트롤러는 관문(?) 같은 역할만 하는 친구라서, 입출력 자체는 App.java에서 처리하고, 컨트롤러는 서비스로 넘겨주는 역할만 수행, 나머지 로직은 서비스에서 시행하는 게 좋지 않을까 싶습니다.
> 
> 수고 많으셨습니다!

devmizz 컨트롤러에 전달말 하는 코드가 더 가독성이 좋을 것 같네요. 리뷰 해주셔서 감사합니다 ^_^
