### ISSUE TITLE
코드 리뷰 남깁니다!

### ISSUE THREAD

**Issue by ahah525** [jmjmjames/ssg-toy-project#3]
# 좋은점
- ReadMe에 간단하게 구현 기능을 써놓으셔서 나중에 보기도 편할 것 같아요!
- 직접 짜신 테스트 코드가 많아서 좋은 것 같아요!

# 아쉬운 점
- 레이어별로 디렉토리 분리를 하면 더 보기 좋을 것 같아요!

수고하셨고 많이 배우고 갑니다!

**Comment by jmjmjames** [comment]
아쉬운 점 얘기해주셔서 감사합니다. 일단 간단한 구조여서 레이어 별로 분리하지 않았는데 가독성이 좀 부족 한 것같네요 ㅠ
