### ISSUE TITLE
리뷰 남깁니다.

### ISSUE THREAD

**Issue by ChangMinSuh** [jmjmjames/ssg-toy-project#5]
어느 파일을 보더라도 stream함수를 잘 응용하신다는 생각이 많이 듭니다.

전반적으로 controller, service, repository 파일도 잘 구분되어 나누어져 있네요!

개별로 저장한 json파일을 .gitignore를 이용해 숨기는 부분 또한 좋았습니다.

고생하셨습니다!

**Comment by jmjmjames** [comment]
창민님 코드 리뷰 감사합니다 .😀
