### ISSUE TITLE
리뷰 남겨봅니다`

### ISSUE THREAD

**Issue by kimdonghyeon3** [jmjmjames/ssg-toy-project#6]
와... 사실 stream 배우고 제대로 연습을 못해봤는데 프로젝트에 직접 적용해보신게 대단합니다.
stream으로 json 파싱 구현을 보니 훨씬 깔끔하게 정리가 되고 역시 흐름대로 따라갈 수 있어서 좋았던 것 같습니다. 테스트 케이스도 다양하게 작성해 주신 것 같아서 많이 참고하고 갑니다~

**Comment by jmjmjames** [comment]
동현님 코드 리뷰 감사합니다!!
