### ISSUE TITLE
송용호 코드리뷰

### ISSUE THREAD

**Issue by nette74** [jmjmjames/ssg-toy-project#7]
능숙하고 간결한 코드를 볼 수 있었습니다. 모든 기능이 간결하게 구현되어 있고 깔끔해서 보기 좋았습니다. 아쉬운 점은 조금더 풀어 쓰거나 주석처리로 코드 가독성을 높이면 더 좋을 것 같습니다!

**Comment by jmjmjames** [comment]
답변주셔서 감사합니다. ^^
